### PR TITLE
Proxy the hosted Supermemory MCP server instead of running a local one

### LINKED ISSUE #13: Cloud Agents: MCP discovery fails because CURSOR_PLUGIN_ROOT is not expanded
## Summary
On Cursor Cloud Agents, the plugin MCP never starts. Tool discovery fails with status `error` ("failed during live tool discovery").

## Root cause
`mcp.json` launches:

```json
{
  "command": "node",
  "args": ["${CURSOR_PLUGIN_ROOT}/dist/cli.js", "mcp"]
}
```

Desktop expands `${CURSOR_PLUGIN_ROOT}`. Cloud Agents inject the literal string into the exec-daemon `--mcp-config`, so Node tries to load:

`/workspace/${CURSOR_PLUGIN_ROOT}/dist/cli.js`

Reproduced with `node '${CURSOR_PLUGIN_ROOT}/dist/cli.js' mcp`.

Running the same CLI with an absolute plugin path works: `initialize` + `tools/list` returns all 8 tools without needing auth at discovery time.

## Auth note
Even after fixing the path, Cloud Agents cannot complete the browser OAuth flow (`localhost:19878` callback / `mcp_auth` times out). Cloud needs `SUPERMEMORY_API_KEY` (or the remote HTTP MCP at `https://mcp.supermemory.ai/mcp`).

## Suggested fixes
1. Ship a self-resolving launcher in `mcp.json` that falls back to discovering the install under `~/.cursor/plugins/...` when `CURSOR_PLUGIN_ROOT` is unset/unexpanded.
2. Document Cloud Agent setup: environment secret `SUPERMEMORY_API_KEY` + stdio override, or HTTP MCP `https://mcp.supermemory.ai/mcp`.
3. Longer-term: prefer HTTP MCP for cloud (matches Linear/Slack/Granola/Context7 plugins).

Happy to contribute a launcher PR if useful.

### PR DESCRIPTION
**Pull request by MaheshtheDev**
Cursor was the only plugin running its own MCP server. `claude-supermemory` and `codex-supermemory` both ship a thin stdio proxy to `https://mcp.supermemory.ai/mcp` authenticated with the credentials their hooks already store, while this repo implemented 8 `supermemory_*` tools locally against `api.supermemory.ai`. That divergence is what makes #13 fatal on Cloud Agents: the local server needs a resolved plugin path on disk *and* an interactive browser login, and a cloud agent has neither.

## Transport

`src/mcp-proxy.ts` replaces `src/mcp-server.ts`: it forwards JSON-RPC lines to the hosted server with the `sm_` key from `loadConfig()`, preserves ordering through a promise queue, tracks `Mcp-Session-Id`, and unwraps SSE frames back into stdout lines. `SUPERMEMORY_MCP_URL` overrides the endpoint for self-hosted setups. `dist/cli.js mcp` still starts it, so every existing config entry keeps working, and the `@modelcontextprotocol/sdk` and `supermemory` dependencies plus `src/client.ts` are gone with the local implementation.

Agents now see the same tools Claude Code and Codex see — `search_memory`, `add_memory`, `listMemories`, `listDocuments`, `getDocument`, `listSpaces`, `whoAmI` — so the rule, the three skills, the context-gatherer agent, and the README tool table are rewritten against those names. The config tools (`supermemory_get_config`, `supermemory_set_config`, `supermemory_containers`) have no hosted equivalent and drop out; `/supermemory-config` and `cli.js status` already cover that ground.

## Keeping tool writes in the project's container

The hosted server writes to the account's active space unless a call passes `containerTag`, while the hooks read and write this repository's container tag. Left alone, a memory saved through `add_memory` would be invisible to session recall. `formatContainerDirective` now states the tag and the requirement in one place, the session-start hook emits it even when no profile facts came back (previously that case injected nothing at all), and the rule, skills, and agent all instruct passing it — the same approach `claude-supermemory`'s recall directive takes.

`approve-memory` matched `/supermemory/i` on the tool name, which no longer matches bare hosted names like `search_memory`. It now also recognises the hosted read-only tools under any server prefix, and leaves unprefixed writes to the normal approval path.

## Cloud Agents

`cli.js mcp-install` writes a `supermemory` entry into `~/.cursor/mcp.json` with an absolute interpreter and script path, merging into whatever is already there. Cloud Agents run it once in the environment install step and set `SUPERMEMORY_API_KEY`, which covers both halves of #13 — no `${CURSOR_PLUGIN_ROOT}` expansion and no browser login. The README documents it.

## Verification

`bun run build`, `bun run typecheck`, and `bun test` all pass (24 tests). New tests cover SSE unwrapping, forwarding with the bearer header against a stub server, the unauthenticated JSON-RPC error, the installer's merge behaviour, the container directive, and the approval matcher. I also drove `dist/cli.js mcp` against the live endpoint with an invalid key and got a clean `-32000` error rather than a crash.

Closes #13.

### CODE REVIEW

**Comment by MaheshtheDev** [comment]
> Written by Claude (Opus 5), reviewed and sent by @maheshthedev.

Tested this locally and pushed one commit (63bfd8e). Summary of what I verified and what I changed.

## Verified working

Built and ran the proxy against the live endpoint from a clean worktree:

- `bun run build`, `bun run typecheck`, `bun test` all pass
- No `Bun.*` globals survive into `dist/` under `--target node` (this broke npm users before, so worth stating explicitly)
- `node dist/cli.js mcp` → real `initialize` + `tools/list` against `mcp.supermemory.ai`, 15 tools back
- Real `search_memory` call with an explicit `containerTag` returns the right space
- Invalid key → clean `-32000 Invalid or expired token`, no crash
- `mcp-install` merges into an existing `~/.cursor/mcp.json` without touching the other entries

Also ran it in real Cursor. Once the old marketplace build was out of the way, the hosted tool names show up and `containerTag` is passed. The transport half of this PR does what it says.

## Why I pushed a commit

The PR closes #13, but `mcp.json` was unchanged:

```json
{ "command": "node", "args": ["${CURSOR_PLUGIN_ROOT}/dist/cli.js", "mcp"] }
```

That line is what #13 reports as the root cause. The PR worked around it with a manual `mcp-install` step in the Cloud Agent install script rather than fixing it, and a step people skip fails exactly the way the issue describes.

The documented command had its own problem:

```bash
node "${CURSOR_PLUGIN_ROOT:-.}/dist/cli.js" mcp-install
```

`:-.` falls back to the working directory. I ran it with `CURSOR_PLUGIN_ROOT` unset from a directory that wasn't the plugin folder and got `Cannot find module`. It only works if the agent happens to be standing in the plugin directory, which isn't stated anywhere.

**63bfd8e** makes the entry self-resolving: it launches `node -e` with no path of its own, then finds the install from `CURSOR_PLUGIN_ROOT` when that actually resolved, else `~/.cursor/plugins/local`, else any cached marketplace copy. I ran it with `CURSOR_PLUGIN_ROOT` set to the literal unexpanded string (the exact failure in #13) and got a full handshake with all 15 tools.

`SUPERMEMORY_API_KEY` is now the only required Cloud Agent step. `mcp-install` stays for environments that reach neither location. README updated.

Four tests run the launcher the way Cursor does — the inlined script is a JSON string, so nothing else typechecks it.

## Three things I did not change

**1. README lists 7 tools, the server returns 15.** Undocumented: `save-memory`, `guided-save`, `upload-file`, `prepare-file-upload`, `memory-graph`, `fetch-graph-data`, `select-space`, `set-active-tag`. The rule, skills and agent were all written against the 7, so nothing tells the model to pass `containerTag` on the other 8 — and `save-memory` / `guided-save` are writes, so they would land in the wrong space.

**2. The plugin's skills lose a name collision.** They are `memory-search` / `memory-save` / `memory-init`, while `~/.codex/skills/` ships `supermemory-search`, `supermemory-save`, and so on. Across four Cursor sessions the model opened the Codex skill or an unrelated repo-level `supermemory` skill before finding the plugin's. Harmless so far (the tool calls still went to the right server), but it is a wasted read every time. Renaming is cheap while these three files are already being rewritten here.

**3. Hosted tool names mix three conventions** — `search_memory` and `add_memory` are snake_case, `listMemories` / `whoAmI` are camelCase, the remaining eight are kebab-case. That belongs to the hosted server, not this PR. Worth a separate issue; `_` is the better target since hosts join namespaces with underscores, and `approve-memory.ts` already treats `/`, `:` and `_` as prefix boundaries but not `-`.

## Unrelated bug worth knowing about

The `containerTag` directive in `session-start.ts` is correct — run by hand it emits the right tag in 1.65s. But it never reaches the model, because Cursor is not loading plugin hooks at all:

```
Claude Code hooks disabled (thirdPartyExtensibilityEnabled off)
Loaded 24 user hook(s) ...
Found 3 hook(s) to execute for step: sessionStart
```

In Cursor 3.20.17 `loadPluginHooks()` sits behind `thirdPartyExtensibilityEnabled`, and that one flag gates both Claude Code hooks and every plugin hook. With it off, no plugin hook runs. The three that executed were all from `~/.cursor/hooks.json`.

This predates the PR — I confirmed the same silence on the old 1.1.0 build before installing this branch. Not a blocker, but the `containerTag` fix only half-lands for anyone with that flag off, and the model then guesses the tag (it produced `repo_mono` instead of `repo_mono__a4c534558b509abb` in one session). Probably its own issue.

**Comment by MaheshtheDev** [comment]
> Written by Claude (Opus 5), reviewed and sent by @maheshthedev.

Follow-up to my last comment — I only fixed `mcp.json` there and missed that the same variable was load-bearing in four documented commands. Pushed **f50dd3c**.

`CURSOR_PLUGIN_ROOT` is set by Cursor for plugin hooks. It is not set in the user's shell, so every one of these expanded to `node "/dist/cli.js"`:

```
README.md:14                     login
commands/supermemory-setup.md    login
commands/supermemory-status.md   status
commands/supermemory-logout.md   logout
```

Reproduced with an empty environment:

```
$ node "${CURSOR_PLUGIN_ROOT}/dist/cli.js" login
node:internal/modules/cjs/loader:1479
  throw err;        # Cannot find module '/dist/cli.js'
```

Each had the same escape hatch — "if `CURSOR_PLUGIN_ROOT` is unset, run `node dist/cli.js login` from the installed plugin directory" — which leaves the reader to find a directory that is either `~/.cursor/plugins/local/cursor-supermemory` or a hashed path under `~/.cursor/plugins/cache/<marketplace>/cursor-supermemory/<sha>/`. All four now resolve the install the same way `mcp.json` does and work from any directory.

I also fixed a line I introduced in the previous commit. The Cloud Agent fallback read `node "$(dirname "$0")/dist/cli.js" mcp-install`, where `$0` is the environment's install script, not the plugin. Same class of mistake as the one being fixed.

Last, the tool table listed 5 rows against the 15 tools `tools/list` actually returns. The undocumented ones include writes (`save-memory`, `guided-save`, `upload-file`), and `select-space` / `set-active-tag` mutate account-wide state, which matters given the rest of this PR is about keeping writes inside the project's container. They are named now, with the first five marked as the set the rule, skills, and agent actually drive.

Verified after the change: typecheck clean, 28 tests pass, and every command block in `README.md` and `commands/*.md` executes from an empty environment and an unrelated working directory.

**One thing I deliberately left alone.** All six entries in `hooks/hooks.json` still use `${CURSOR_PLUGIN_ROOT}`:

```json
"command": "node \"${CURSOR_PLUGIN_ROOT}/dist/session-start.js\""
```

Expanding that variable for hooks is its documented job, and #13 is specifically about `mcp.json` reaching the exec daemon, so I have no evidence these break. I could not test it either way on this machine — plugin hooks are not loading at all here, for the unrelated `thirdPartyExtensibilityEnabled` reason in my previous comment. Worth a look from someone who can run a Cloud Agent, since if the variable is unexpanded there too, the hooks fail silently rather than loudly.

**Review by Dhravya — APPROVED** [review]
